apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gestion-herencia-https
  namespace: herencia
spec:
  entryPoints:
    - web
    - websecure
  routes:
  # Ruta para API - más específica, debe ir primero
  - match: Host(`northr3nd.duckdns.org`) && PathPrefix(`/herencia/api`)
    kind: Rule
    services:
    - name: gestion-herencia-backend
      port: 3000
    middlewares:
    - name: strip-herencia-api
  # Ruta para Frontend - menos específica
  - match: Host(`northr3nd.duckdns.org`) && PathPrefix(`/herencia`)
    kind: Rule
    services:
    - name: gestion-herencia
      port: 80
  tls:
    secretName: northr3nd-tls
